services:
  web:
    build: .
    restart: always
    expose:
      - ${PORT}
    environment:
      PORT: ${PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hawari.rule=Host(`hawari.dev`)"
      - "traefik.http.routers.hawari.entrypoints=websecure"
      - "traefik.http.routers.hawari.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.hawari.loadbalancer.server.port=${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${PORT}/api/heartbeat"]
      start_period: 5s
      interval: 3600s
      timeout: 5s
      retries: 5
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
